CREATE DATABASE IF NOT EXISTS `SOAPBOX`
   DEFAULT CHARSET = utf8mb4
   COLLATE = utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `OPENFIRE`
   DEFAULT CHARSET = utf8mb4
   COLLATE = utf8mb4_unicode_ci;

CREATE USER 'soapbox'@'localhost' IDENTIFIED BY 'SOAPBOX-SQL-PASSWORD';
CREATE USER 'openfire'@'localhost' IDENTIFIED BY 'OPENFIRE-SQL-PASSWORD';

GRANT ALL PRIVILEGES ON SOAPBOX.* TO 'soapbox'@'localhost'; 
GRANT ALL PRIVILEGES ON OPENFIRE.* TO 'openfire'@'localhost'; 
